### ISSUE TITLE
AttributeError: 'list' object has no attribute 'item'

### ISSUE THREAD

**Issue by 0xpranjal** [AmineDiro/Adversarial-Attacks#4]
While running the "Adversarial Whitebox Attacks.ipynb" file. I got the following error. Please help me resolve this.
<img width="1073" alt="Screenshot 2021-07-04 at 5 20 07 PM" src="https://user-images.githubusercontent.com/50989807/124383810-16551780-dcec-11eb-86e0-bc5b27866407.png">

**Comment by AmineDiro** [comment]
Hello, 
Sorry for the delay, i fixed the code, pls pull to update with the latest changes.

Don't hesitate if you have any issue

**Comment by 0xpranjal** [comment]
Thanks a lot for replying back and resolving the issue. It will definitely help me to continue my research.
